# Generated by Django 4.2.1 on 2024-09-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchmode_id', models.IntegerField(unique=True, verbose_name='Watchmode ID')),
                ('imdb_id', models.CharField(max_length=15, unique=True, verbose_name='IMDb ID')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='TMDb ID')),
                ('tmdb_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show')], max_length=10, verbose_name='TMDb Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Movie ID Mapping',
                'verbose_name_plural': 'Movie ID Mappings',
                'indexes': [models.Index(fields=['watchmode_id'], name='api_movieid_watchmo_be002f_idx'), models.Index(fields=['imdb_id'], name='api_movieid_imdb_id_2fac4b_idx'), models.Index(fields=['tmdb_id'], name='api_movieid_tmdb_id_837dc9_idx')],
            },
        ),
    ]
