# Generated by Django 4.2.1 on 2024-09-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movieidmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieidmapping',
            name='year',
        ),
    ]
