# Generated by Django 4.2.1 on 2024-09-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movieidmapping_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingavailability',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='streamingavailability',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='streamingavailability',
            unique_together={('movie', 'platform', 'region')},
        ),
        migrations.RemoveField(
            model_name='streamingavailability',
            name='available_since',
        ),
    ]
