# Generated by Django 4.2.1 on 2024-09-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_movie_backdrop_path_alter_movie_original_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
