# Generated by Django 4.2.1 on 2024-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_movie_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
