# Generated by Django 4.2.1 on 2024-09-11 14:58

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=api.models.AzureMediaStorage(), upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='streaming_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
