# Generated by Django 4.2.1 on 2024-09-11 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userprofile_streaming_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='streaming_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
