# Generated by Django 4.2.1 on 2024-09-11 15:21

from django.db import migrations

def populate_genres(apps, schema_editor):
    Movie = apps.get_model('api', 'Movie')
    Genre = apps.get_model('api', 'Genre')

    for movie in Movie.objects.all():
        if movie.old_genres:
            genre_names = [g.strip() for g in movie.old_genres.split(',')]
            for genre_name in genre_names:
                genre, _ = Genre.objects.get_or_create(name=genre_name)
                movie.genres.add(genre)

def reverse_populate_genres(apps, schema_editor):
    Genre = apps.get_model('api', 'Genre')
    Genre.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_genre_movie_old_genres_remove_movie_genres_and_more'),  # replace with the actual previous migration
    ]

    operations = [
        migrations.RunPython(populate_genres, reverse_populate_genres),
    ]