# Generated by Django 4.2.1 on 2024-09-11 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_group_groupmember_group_members_usermoviepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
