# Generated by Django 4.2.1 on 2024-09-12 00:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_userprofile_preferred_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='genres_preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='group',
            name='streaming_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
