version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=movie-matcher
      - DB_USER=admin2
      - DB_PASS=admin3
      - SECRET_KEY=your-secret-key
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - postgres
      - redis
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: movie-matcher
      POSTGRES_USER: admin2
      POSTGRES_PASSWORD: admin3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2-alpine
    name: movie-matcher-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: